//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRelay.WcfHost.NextDataRelayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NextDataRelayService.IDataRelay")]
    public interface IDataRelay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRelay/Send", ReplyAction="http://tempuri.org/IDataRelay/SendResponse")]
        bool Send(byte[] package);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRelay/KnockKnock", ReplyAction="http://tempuri.org/IDataRelay/KnockKnockResponse")]
        bool KnockKnock(byte[] package);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataRelayChannel : DataRelay.WcfHost.NextDataRelayService.IDataRelay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataRelayClient : System.ServiceModel.ClientBase<DataRelay.WcfHost.NextDataRelayService.IDataRelay>, DataRelay.WcfHost.NextDataRelayService.IDataRelay {
        
        public DataRelayClient() {
        }
        
        public DataRelayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataRelayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRelayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRelayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Send(byte[] package) {
            return base.Channel.Send(package);
        }
        
        public bool KnockKnock(byte[] package) {
            return base.Channel.KnockKnock(package);
        }
    }
}
